// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Tue Oct 16 17:40:59 2018

DataMemory DataMemory_inst
(
	.dataIn(dataIn_sig) ,	// input [31:0] dataIn_sig
	.address(address_sig) ,	// input [31:0] address_sig
	.wsign(wsign_sig) ,	// input  wsign_sig
	.clock(clock_sig) ,	// input  clock_sig
	.dataOut(dataOut_sig) 	// output [31:0] dataOut_sig
);

